//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JigDrawing
    {
        public int DrawingID { get; set; }
        public int JigID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string Version { get; set; }
        public string Note { get; set; }
        public string DrawingName { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    
        public virtual Jig Jig { get; set; }
    }
}
