//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JigMaintainHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JigMaintainHistory()
        {
            this.JigMaintainChecklist = new HashSet<JigMaintainChecklist>();
            this.MaintainSpareUsage = new HashSet<MaintainSpareUsage>();
        }
    
        public int MaintainID { get; set; }
        public int JigID { get; set; }
        public Nullable<System.DateTime> MaintainDate { get; set; }
        public Nullable<int> Maintainer { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> NextMaintainDate { get; set; }
        public string Remark { get; set; }
    
        public virtual Jig Jig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JigMaintainChecklist> JigMaintainChecklist { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintainSpareUsage> MaintainSpareUsage { get; set; }
    }
}
