//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JigMaintainChecklist
    {
        public int ChecklistID { get; set; }
        public int MaintainID { get; set; }
        public int MaintainItemID { get; set; }
        public string Result { get; set; }
        public string Remark { get; set; }
        public string SpareUsed { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual MaintainItem MaintainItem { get; set; }
        public virtual JigMaintainHistory JigMaintainHistory { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
