//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JigPartList
    {
        public int ID { get; set; }
        public int JigID { get; set; }
        public int SpareID { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Note { get; set; }
    
        public virtual Jig Jig { get; set; }
        public virtual SparePartStocks SparePartStocks { get; set; }
    }
}
