//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JigRepairHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JigRepairHistory()
        {
            this.RepairSpareUsage = new HashSet<RepairSpareUsage>();
        }
    
        public int RepairID { get; set; }
        public int JigID { get; set; }
        public Nullable<System.DateTime> RepairDate { get; set; }
        public string Problem { get; set; }
        public string Action { get; set; }
        public Nullable<int> Technician { get; set; }
        public string FilePath { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    
        public virtual Jig Jig { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairSpareUsage> RepairSpareUsage { get; set; }
    }
}
