//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintainSpareUsage
    {
        public int ID { get; set; }
        public int MaintainID { get; set; }
        public int SpareID { get; set; }
        public Nullable<int> QtyUsed { get; set; }
    
        public virtual JigMaintainHistory JigMaintainHistory { get; set; }
        public virtual SparePartStocks SparePartStocks { get; set; }
    }
}
