//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintainItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintainItem()
        {
            this.JigMaintainChecklist = new HashSet<JigMaintainChecklist>();
        }
    
        public int MaintainItemID { get; set; }
        public string JigType { get; set; }
        public string ItemName { get; set; }
        public string ItemGroup { get; set; }
        public string Frequency { get; set; }
        public string Standard { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JigMaintainChecklist> JigMaintainChecklist { get; set; }
    }
}
