//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartReceipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SparePartReceipts()
        {
            this.SparePartReceiptDetails = new HashSet<SparePartReceiptDetails>();
        }
    
        public int ReceiptID { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SparePartReceiptDetails> SparePartReceiptDetails { get; set; }
    }
}
