//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartReceiptDetails
    {
        public int DetailID { get; set; }
        public int ReceiptID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public int SpareID { get; set; }
        public int QtyReceived { get; set; }
    
        public virtual SparePartReceipts SparePartReceipts { get; set; }
        public virtual SparePartRequests SparePartRequests { get; set; }
        public virtual SparePartStocks SparePartStocks { get; set; }
    }
}
