//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SparePartRequests()
        {
            this.SparePartApprovals = new HashSet<SparePartApprovals>();
            this.SparePartReceiptDetails = new HashSet<SparePartReceiptDetails>();
            this.SparePartUse = new HashSet<SparePartUse>();
        }
    
        public int RequestID { get; set; }
        public int SpareID { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public int QtyRequested { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SparePartApprovals> SparePartApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SparePartReceiptDetails> SparePartReceiptDetails { get; set; }
        public virtual SparePartStocks SparePartStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SparePartUse> SparePartUse { get; set; }
    }
}
