//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartUse
    {
        public int UseID { get; set; }
        public int SpareID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public int Qty { get; set; }
        public string IssuedTo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Remark { get; set; }
    
        public virtual SparePartRequests SparePartRequests { get; set; }
        public virtual SparePartStocks SparePartStocks { get; set; }
    }
}
