//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SparePart_WaitingRequestStatus
    {
        public int SpareID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalRequested { get; set; }
        public int TotalReceived { get; set; }
        public Nullable<int> QtyPending { get; set; }
        public Nullable<int> PendingRequestCount { get; set; }
    }
}
