//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jig_system_control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SparePart_PendingRequests
    {
        public int RequestID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int QtyReceived { get; set; }
        public Nullable<int> QtyPending { get; set; }
        public string Status { get; set; }
        public int SpareID { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ApprovedQty { get; set; }
    }
}
